title: "ASA Biopharmaceutical Section"
description: "Oncology Treatment Switch Workstream"
baseurl: "/trtswitch-website"
url: "https://shreyasreeram27.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
# Remove the theme line completely - let GitHub Pages use default

# Navigation menu items
header_pages:
  - index.md
  - objectives.md
  - methods.md
  - resources.md

# Custom variables for your site
workstream:
  title: "Oncology Treatment Switch Workstream"
  description: "Addressing the impact of treatment switch on long-term outcomes in oncology clinical trials"

# Plugins (GitHub Pages supports these automatically)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
